---
global:
  pattern: layered-zero-trust
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: coco-dev
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
